project: pi3
snaps:
  kernel: pi2-kernel
  os: ubuntu-core
  gadget: pi3
configs:
  arch: armhf
  baseimage: base.img
  swap: on
  swapsize: 1024
  release: 16
  partition-type: mbr
  bootloader: u-boot
recovery:
  type: factory_install
  installerfslabel: INSTALLER
  recoverysize: 768
  filesystem-label: ESP
  oem-preinst-hook-dir: OEM_pre_install_hook
  oem-postinst-hook-dir: OEM_post_install_hook
  oem-prereboot-hook-dir: OEM_pre_reboot_hook
  oemlogdir: MFGMEDIA
